### ISSUE TITLE
Tracking Issue for "Trusted Publishing Support"

### ISSUE THREAD

**Issue by Turbo87** [rust-lang/crates.io#10247]
This is a tracking issue for the RFC "crates.io: Trusted Publishing Support" (rust-lang/rfcs#3691).

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.
Discussion comments will get marked as off-topic or deleted.
Repeated discussions on the tracking issue may lead to the tracking issue getting locked.

### Steps

- [x] Implement backend support in crates.io
  - [x] Add database table for (GitHub Actions) trusted publishing configs (https://github.com/rust-lang/crates.io/pull/11062)
  - [x] Implement API endpoint to create trusted publishing config (incl. email notification) (https://github.com/rust-lang/crates.io/pull/11113)
  - [x] Implement API endpoint to delete trusted publishing config (incl. email notification) (https://github.com/rust-lang/crates.io/pull/11209)
  - [x] Implement API endpoint to list trusted publishing configs (https://github.com/rust-lang/crates.io/pull/11230)
  - [x] Add database table for temporary access tokens (https://github.com/rust-lang/crates.io/pull/11062)
  - [x] Add database table for used OIDC token IDs (https://github.com/rust-lang/crates.io/pull/11062)
  - [x] Implement API endpoint to exchange GHA OIDC token for temporary access token (https://github.com/rust-lang/crates.io/pull/11131)
  - [x] Adjust exchange API endpoint to save used OIDC token IDs and reject replays (https://github.com/rust-lang/crates.io/pull/11131)
  - [x] Implement API endpoint to revoke temporary access token (https://github.com/rust-lang/crates.io/pull/11234)
  - [x] Adjust publish API endpoint to accept temporary access tokens (https://github.com/rust-lang/crates.io/pull/11294)
  - [x] Implement regular background job to delete expired temporary access tokens and OIDC token IDs (https://github.com/rust-lang/crates.io/pull/11222)
  - [x] Adjust GitHub Secret Scanning endpoints to work with temporary access tokens too (https://github.com/rust-lang/crates.io/pull/11405)
- [x] Implement frontend UI in crates.io
  - [x] Implement route to list trusted publishing configs (https://github.com/rust-lang/crates.io/pull/11398)
  - [x] Implement route to create trusted publishing config (https://github.com/rust-lang/crates.io/pull/11398)
  - [x] Implement button to delete trusted publishing config (https://github.com/rust-lang/crates.io/pull/11398)
  - [x] Write documentation for the Trusted Publishing feature (https://github.com/rust-lang/crates.io/pull/11414)
- [x] Implement GitHub Action (https://github.com/rust-lang/crates-io-auth-action/pull/1)

### Unresolved Questions

None? (see https://rust-lang.github.io/rfcs/3691-trusted-publishing-cratesio.html#unresolved-questions)

**Comment by Turbo87** [comment]
I guess now that this is implemented and officially announced we can close the issue 🎉
