### ISSUE TITLE
Tracking issue for updating dependencies

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/crates.io#1265]
## API Changes

These require code changes to address API changes.

* [x] `tar` - a80193e
* [x] `openssl` part 1 - b4fc94f
* [x] `openssl` part 2 - 8036a78
* [x] `hyper` - #1289
* [x] `flate2` - bd0cd6d
* [x] `envlogger` - ac9d73d
* [x] `hex` - dccee42
* [x] `lettre` - 822735e
* [x] `oauth2` - #1842
* [x] `jemalloc` and `jemalloc-ctl` - to 0.3.2 - #1953 and #1956
* [x] `cookie` - 0.11 to 0.12, will also need to upstream a change to `conduit-cookie` #2208
* [x] `dotenv` - 0.11 to 0.15 - #1917
* [x] `hex` - 0.3 to 0.4 #2256

[oauth2-2.0-alpha]: https://github.com/jtgeibel/crates.io/commit/7de5a023cb211138b09485320bedc3e4f3a17fd2

## Version bump

These should just be a version bump in `Cargo.toml`.

* [ ] `url` - 1.7 to 2.1 (needs to wait for newer oauth2 3.0 alpha)
* [x] `comrak` - 0.4 to 0.7 - #2513
* [x] `dotenv` - 0.10 to 0.11 - #1391
* [x] `itertools` - 0.6 to 0.7
* [x] `base64` - 0.6 to 0.9
* [x] `log` - 0.3 to 0.4
* [x] `comrak` - 0.2 to 0.4 #1664
* [x] `ammonia` - 1.0 to 2.0 #1664
* [x] `git2` - 0.6 to 0.8 #1663
* [x] `env_logger` - 0.5 to 0.7 - #2236
* [x] `docopt` - 0.8 to 1.1 #1812
* [x] `toml` - 0.4 to 0.5 #2430
* [x] `git2` - 0.8 to 0.13 #2467
* [x] `ammonia` - 2.0 to 3.0 - #1876
* [x] `rand` - 0.6 to 0.7 - #2512
* [x] `base64` - 0.9 to 0.11 (also bump in s3) #2208
* [x] `parking_lot` - 0.7 to 0.10 - #2223
* [x] `handlebars` - 2 to 3 #2259

### `conduit-git-http-backend`

We could switch to `libflate` however it is no longer pulled in by `reqwest` by default and we've consolidated on a single version of `flate2` so this isn't a priority.

* [x] Bump to `flate2` 1.0 - #2208

### `conduit-cookie`

* [x] `base64` - we can bump to 0.11 in `src/s3`, but the old version is still pulled in and it would be nice to land conduit-rust/conduit-cookie#6 - #2208
* [x] `cookie` - from 0.11 to 0.12 - #2208
* [x] `ring` - from 0.13 to 0.14 - #2208
* [x] `ring` - from 0.14 to 0.16

**Comment by sgrif** [comment]
@jtgeibel I think we should chat about a plan for this. Want to ping me on gitter and set up a call?

**Comment by jtgeibel** [comment]
@sgrif yeah that sounds good to me.  I've just created a gitter account and will reach out to you there.

**Comment by jtgeibel** [comment]
I'm going to close this as effectively complete after 2+ years! The only remaining update is for `url` 1.7 to 2.1, however this would require bumping to an alpha release of `oauth2`. (We could also update to `base64 0.12` however there is no point in pulling in a 4th version of this crate until it is pulled into the tree via some other dependency.)

There is a bit more work to do to incrementally `cargo update` portions of the dependency tree, but we've already made good progress on that and beyond the exceptions above no changes to `Cargo.toml` remain at this time.

**Comment by carols10cents** [comment]
Hooray!!!! Would we be able to and want to enable dependabot for Rust deps now?

**Comment by jtgeibel** [comment]
> Would we be able to and want to enable dependabot for Rust deps now?

Very soon I hope! We just need to do a `cargo update` to get all semver compatible changes into the lockfile. The last few times we tried this we were getting segfaults in production, but it has been a while since we tried a full update like that and we've made a lot of progress since in updating portions of the tree without issue.

For instance we did a `cargo update -p reqwest --aggressive` which updated a good portion of dependencies. We can probably slice off a few other pieces of functionality like git, serde, and readme rendering. I think we can get there with another 3 PRs or so following this sort of conservative approach.
