### ISSUE TITLE
Tracking issue for upgrading to `heroku-18` stack

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/crates.io#1868]
The `heroku-16` stack is supported through [April 2021](https://devcenter.heroku.com/articles/heroku-16-stack#support-period) so we should migrate to `heroku-18` before then. At this time (September 2020), the `heroku-20` stack has not reached general availability.

## Checklist

- [x] Migrate staging to 18.04
- [x] Migrate production to 18.04
- [x] #1867 - Migrate CI to 18.04 

## Original Migration Details

I'm opening this issue to document the process of bumping to the `heroku-18` stack (from `heroku-16`)  on my staging environment.

After bumping to the newest stack in the Heroku GUI, the changes take effect on the next deploy.  The next build then failed with a linking error, due to missing openssl symbols.  The build was using cached build files that were built on an older `xenial`-based system.

Following the instructions on the [help page], I used the following commands clear the build cache and force a new deploy:

```console
$ heroku plugins:install heroku-repo
$ heroku repo:purge_cache -a $appname
$ git commit --allow-empty -m "Force new deploy on heroku-18"
$ git push heroku master
```

After a clean build the site appears to operate normally, however I haven't yet tested all of the functionality, such as publishing.

If we decide to bump to the `heroku-18` stack, then we'll also want to bump our CI to `bionic` to match.

[help page]: https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache
