### ISSUE TITLE
Tracking issue for enabling capacity enforecment

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/crates.io#2496]
Based on a temporary deploy of the new `BalanceCapacity` middleware it looks like our traffic often has large spikes of request activity. Therefore, the simple heuristics currently used by the middleware likely need tweaking before we can enable enforcement.

In #2495 the `WEB_CAPACITY_REPORT_ONLY` environment variable is added which puts the middleware into report-only mode. Here are some of the improvements we will likely need to make before enabling enforcement in production:

- [ ] After a deploy, there is expected to be a large backlog of pending requests that hit the backend in quick succession. The logic could be tweaked to avoid dropping requests during the first 30 seconds (or so) after launch.
- [ ] We may want to add a special case for the crate publishing endpoint, in addition to the special case for download requests.
- [ ] We could design the enforcement logic to be based on the actual load on the primary database pool. The current implementation ignores the existence of the read-only replica. We could also move more read-only requests to the read-only pool.

**Comment by jtgeibel** [comment]
To follow up on this, below is a graph of log activity with the new `would_reject` attribute over a 48 hour period. At this scale, each point represents a period of 24 minutes.

![Screenshot_2020-05-13 All Apps - Papertrail](https://user-images.githubusercontent.com/22186/81878587-7e7bf380-9556-11ea-8ad0-7a8b8bcd4816.png)

Many of these requests appear to originate from shields.io. By filtering out that user agent, we have the following:

![Screenshot_2020-05-13 All Apps - Papertrail(1)](https://user-images.githubusercontent.com/22186/81878668-b2efaf80-9556-11ea-8e32-ff84995a6005.png)

I've already reached out to one tool that is responsible for some of the remaining spikes (sending 146 requests in a single 1 second interval in one case).

We do have room to increase the size of the database pool per dyno, however that may limit our ability to scale horizontally. We can currently double our dyno count before we start to approach our database connection limit. I'm not proposing any changes at this time, just wanted to provide an update and some graphs.

**Comment by Turbo87** [comment]
#8451 removed the `BalanceCapacity` middleware since we are no longer serving the download requests through the API. I guess we can close this issue :)
