### ISSUE TITLE
Tracking Issue: Token Scopes

### ISSUE THREAD

**Issue by Turbo87** [rust-lang/crates.io#5443]
This is a tracking issue for the RFC "crates.io Token Scopes" (rust-lang/rfcs#2947).

**Steps:**

Backend: 
- [x] add token scopes to the database (https://github.com/rust-lang/crates.io/pull/5562)
- [x] check token scopes for authenticated endpoints (https://github.com/rust-lang/crates.io/pull/5572)
- [x] implement API support for token scopes (https://github.com/rust-lang/crates.io/pull/5973 and https://github.com/rust-lang/crates.io/pull/6310)

Frontend: 
- [x] create a dedicated token creation route (https://github.com/rust-lang/crates.io/pull/6395)
- [x] implement support for endpoint scopes to the route (https://github.com/rust-lang/crates.io/pull/6428)
- [x] implement support for crates scopes to the route (https://github.com/rust-lang/crates.io/pull/6432)
- [x] show token scopes in the API token list (https://github.com/rust-lang/crates.io/pull/6450)

The exact details of these steps are still tbd. Feel free to discuss here or contact the @rust-lang/crates-io team if you have any questions. It might be best to discuss the plans first before working on and opening a PR 😉 

**Unresolved questions:**

- Are there more scopes that would be useful to implement from the start?
- Is the current behavior of crate scopes on endpoints that don't interact with
  crates the best, or should a token with crate scopes prevent access to
  endpoints that don't act on crates?

**Comment by mbhall88** [comment]
Was there a reason for limiting the patterns allowed for token scope to, for example, `serde*`? What I mean is the wildcard is a suffix here, but `*serde` is not allowed - i.e., a wildcard prefix.

My use case is I have a workspace with binary `foo` and a library `libfoo`. I'd like to be able to create a crates API token scoped to `*foo` but his is not possible with the current scoping patterns.

(Apologies if this is not the right place to ask this question)

**Comment by Turbo87** [comment]
@mbhall88 mostly for implementation simplicity. you can add multiple scopes to one token though, so this should still be relatively easy to achieve.
